#!/usr/bin/env python3
"""
Signature Math — browse catalog builder (HOOK FILE).

WHEN TO RUN (exact hook): AFTER data/mathdata.json and data/posts.json have
finished flushing on EVERY data drip/run — this script is NOT allowed to run
before or in parallel with the data write, or browse.html/sitemap.xml/api.json
will be stamped one run BEHIND the real counts.

    python3 code/build_browse.py

WHAT IT DOES (idempotent — safe to re-run):
  1. Reads data/mathdata.json (conversion cards, JAH-MATHDATA-######)
     and data/posts.json (canonical documents, JAH-MATH-######).
  2. Writes data/browse_index.json — compact A-Z index for browse.html
     (id, name, cat, letter only; a few KB; browse.html loads it lazily).
  3. Re-stamps the live counts in browse.html (<b id="browsetotal">…</b>)
     AFTER the data flush — regex, fails loud if the stamp target is missing.
  4. Re-stamps the counts block in api.json (math_records, conversion_records,
     total_records) so the boot-time JS counters and the static HTML agree.
  5. Regenerates sitemap.xml from the data:
     home, browse.html, ?doc= x N docs, ?conv= x M cards, api.json, llms.txt,
     data/mathdata.json, data/posts.json, data/browse_index.json.

Do NOT hand-edit sitemap.xml — it is generated by this script.
"""
import json, re, os, html
from datetime import date

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
BASE = "https://justinahiggins614-cmyk.github.io/signature-math"
TODAY = date.today().isoformat()

def load(p):
    with open(os.path.join(ROOT, p), encoding="utf-8") as f:
        return json.load(f)

def main():
    mathdata = load("data/mathdata.json")
    posts = load("data/posts.json")

    n_docs = len(posts)
    n_conv = len(mathdata)
    total = n_docs + n_conv

    ids = [r["id"] for r in mathdata]
    if len(ids) != len(set(ids)):
        raise SystemExit("FAIL: duplicate conversion IDs in data/mathdata.json")
    letters = sorted({r["letter"] for r in mathdata})

    # ---- 1. compact A-Z index for lazy loading ----
    index = []
    for r in mathdata:
        index.append({"id": r["id"], "name": r["name"],
                      "cat": r.get("cat", ""), "letter": r.get("letter", ""),
                      "kind": "conv"})
    for p in posts:
        index.append({"id": p["id"], "name": p["short"],
                      "cat": "Canonical document", "letter": "", "kind": "doc"})
    out = os.path.join(ROOT, "data/browse_index.json")
    with open(out, "w", encoding="utf-8") as f:
        json.dump({"total": total, "updated": TODAY, "records": index}, f)
    print("wrote data/browse_index.json:", total, "records")

    # ---- 2. re-stamp browse.html count (AFTER data flush) ----
    bp = os.path.join(ROOT, "browse.html")
    if not os.path.exists(bp):
        raise SystemExit("FAIL: browse.html not found — nothing to stamp")
    with open(bp, encoding="utf-8") as f:
        bt = f.read()
    new_bt, n = re.subn(
        r'(<b id="browsetotal"[^>]*>)\d+(</b>)',
        lambda m: m.group(1) + str(total) + m.group(2), bt)
    if n == 0:
        raise SystemExit("FAIL: browse.html stamp target <b id=\"browsetotal\"> not found")
    # also stamp the dated line inside browse.html
    new_bt2, n2 = re.subn(
        r'(<p class="stamp"[^>]*>Count stamped )\d{4}-\d{2}-\d{2}( — )',
        lambda m: m.group(1) + TODAY + m.group(2), new_bt)
    if new_bt2 != new_bt or new_bt != bt:
        with open(bp, "w", encoding="utf-8") as f:
            f.write(new_bt2 if new_bt2 != new_bt else new_bt)
    print("stamped browse.html: browsetotal =", total)

    # ---- 3. re-stamp api.json counts ----
    ap = os.path.join(ROOT, "api.json")
    with open(ap, encoding="utf-8") as f:
        at = f.read()
    def setcnt(key, val):
        nonlocal at
        at2, n3 = re.subn(
            r'("%s": )\d+' % re.escape(key),
            lambda m: m.group(1) + str(val), at, count=1)
        if n3 == 0:
            raise SystemExit("FAIL: api.json count key %r not found" % key)
        at = at2
    setcnt("math_records", n_docs)
    setcnt("conversion_records", n_conv)
    setcnt("total_records", total)
    with open(ap, "w", encoding="utf-8") as f:
        f.write(at)
    print("stamped api.json counts: docs=%d conv=%d total=%d" % (n_docs, n_conv, total))

    # ---- 4. regenerate sitemap.xml ----
    urls = ["", "browse.html", "api.json", "llms.txt",
            "data/mathdata.json", "data/posts.json", "data/browse_index.json"]
    for p in posts:
        urls.append("?doc=" + p["id"])
    for r in mathdata:
        urls.append("?conv=" + r["id"])
    lines = ['<?xml version="1.0" encoding="UTF-8"?>',
             '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for u in urls:
        lines.append('  <url><loc>%s/%s</loc><lastmod>%s</lastmod></url>'
                     % (BASE, html.escape(u), TODAY))
    lines.append("</urlset>")
    with open(os.path.join(ROOT, "sitemap.xml"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote sitemap.xml:", len(urls), "URLs")

if __name__ == "__main__":
    main()
